-- ГЕНЕРАТОР db/live-schema.sql.
--
-- db/README.md вимагає перезнімати знімок «тим самим запитом» після кожної
-- міграції — але самого запиту в репозиторії не було, тобто вимога була
-- невиконанною. Тепер він тут.
--
-- Як користуватись:
--   Supabase → SQL Editor → цей файл → Run → єдине поле b64 →
--   прибрати переноси (Postgres ріже base64 кожні 76 символів), розкодувати
--   і покласти в db/live-schema.sql.
--
-- base64 тут не заради таємності (схема публічна), а тому що інакше JSON-
-- відповідь ріже й екранує довгий текст.
--
-- ПОРЯДОК СЕКЦІЙ значущий: таблиці → обмеження → індекси → функції → RLS →
-- політики → тригери → права. Функції стоять перед політиками, бо політики
-- на них посилаються (is_approved).

with cols as (
  select c.relname as tbl,
         string_agg('  ' || a.attname || ' ' || format_type(a.atttypid, a.atttypmod) ||
                    case a.attidentity
                      when 'a' then ' generated always as identity'
                      when 'd' then ' generated by default as identity'
                      else coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '') end ||
                    case when a.attnotnull then ' not null' else '' end,
                    E',\n' order by a.attnum) as body
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname
),
tables as (
  select string_agg('create table if not exists public.' || tbl || E' (\n' || body || E'\n);',
                    E'\n\n' order by tbl) as t from cols
),
constraints as (
  select string_agg('alter table public.' || c.relname || ' add constraint ' || con.conname ||
                    ' ' || pg_get_constraintdef(con.oid) || ';', E'\n'
                    order by c.relname, con.conname) as t
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
),
indexes as (
  select string_agg(i.indexdef || ';', E'\n' order by i.indexname) as t
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint con
                    join pg_class ic on ic.oid = con.conindid
                    where ic.relname = i.indexname)
),
funcs as (
  select string_agg(
           pg_get_functiondef(p.oid) || E';\n' ||
           coalesce((select string_agg('grant execute on function public.' || p.proname ||
                                       '(' || pg_get_function_identity_arguments(p.oid) || ') to ' || g || ';',
                                       E'\n' order by g)
                     from unnest(array['anon','authenticated','service_role']) g
                     where has_function_privilege(g, p.oid, 'execute')), ''),
           E'\n\n' order by p.proname, pg_get_function_identity_arguments(p.oid)) as t
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
),
rls as (
  select string_agg('alter table public.' || c.relname || ' enable row level security;' || E'\n' ||
                    'alter table public.' || c.relname || ' force row level security;', E'\n'
                    order by c.relname) as t
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
policies as (
  select string_agg('create policy ' || pol.polname || ' on public.' || c.relname ||
                    ' as ' || case when pol.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end ||
                    ' for ' || case pol.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT'
                                               when 'w' then 'UPDATE' when 'd' then 'DELETE'
                                               else 'ALL' end ||
                    ' to ' || (select string_agg(r.rolname, ', ' order by r.rolname)
                               from pg_roles r where r.oid = any(pol.polroles)) ||
                    coalesce(E'\n  using (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '') ||
                    coalesce(E'\n  with check (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '') || ';',
                    E'\n\n' order by pol.polname) as t
  from pg_policy pol join pg_class c on c.oid = pol.polrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
),
triggers as (
  select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n' order by t.tgname) as t
  from pg_trigger t join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
),
tgrants as (
  select string_agg('grant ' || g.privilege_type || ' on public.' || g.table_name ||
                    ' to ' || g.grantee || ';', E'\n'
                    order by g.grantee, g.table_name, g.privilege_type) as t
  from information_schema.role_table_grants g
  where g.table_schema = 'public' and g.grantee in ('anon','authenticated','service_role')
),
cgrants as (
  -- Колонкові права. role_table_grants їх НЕ показує, і саме через це
  -- зникнення update на profiles ледь не лишилось непоміченим: у знімку
  -- рядок просто пропав, а нового не зʼявилось.
  select coalesce(string_agg('grant ' || c.privilege_type || ' (' || c.column_name || ') on public.' ||
                             c.table_name || ' to ' || c.grantee || ';', E'\n'
                             order by c.grantee, c.table_name, c.privilege_type, c.column_name),
                  '-- (колонкових прав немає)') as t
  from information_schema.role_column_grants c
  where c.table_schema = 'public' and c.grantee in ('anon','authenticated','service_role')
    and not exists (select 1 from information_schema.role_table_grants g
                    where g.table_schema = 'public' and g.table_name = c.table_name
                      and g.grantee = c.grantee and g.privilege_type = c.privilege_type)
),
jobs as (
  select coalesce(string_agg('-- cron: ' || jobname || '  «' || schedule || '»  ' || command,
                             E'\n' order by jobid), '-- cron: (жодного завдання)') as t
  from cron.job
)
select encode(convert_to(
  '-- =============================================================================' || E'\n' ||
  '-- ЗНІМОК БОЙОВОЇ СХЕМИ  (згенеровано, не редагувати руками)' || E'\n' ||
  '-- =============================================================================' || E'\n' ||
  '-- Генератор: db/dump-live-schema.sql. Порядок секцій значущий:' || E'\n' ||
  '-- таблиці → обмеження → індекси → функції → RLS → політики → тригери → права.' || E'\n' ||
  '-- Функції стоять перед політиками, бо політики на них посилаються (is_approved).' || E'\n' ||
  '--' || E'\n' ||
  '-- Це ДОВІДКА, а не міграція: виконувати цілком по бойовій базі не можна.' || E'\n' ||
  '-- Повний опис — у db/README.md.' || E'\n' ||
  '--' || E'\n' ||
  '-- Знято: ' || current_date || '. ' || version() || ', проєкт ' || current_database() || '.' || E'\n' ||
  '-- =============================================================================' || E'\n\n' ||
  (select t from tables) || E'\n\n-- обмеження\n' ||
  (select t from constraints) || E'\n\n' ||
  (select t from indexes) || E'\n\n-- функції\n\n' ||
  (select t from funcs) ||
  -- Жодна функція public не має execute для PUBLIC (перевірено запитом по
  -- proacl). Postgres дає це право за замовчуванням при create function,
  -- тому в знімку воно мусить бути знято ЯВНО — інакше копія схеми
  -- виявляється дозвільнішою за бойову базу, і перевірка прав це проґавить.
  E'\n\n-- жодна функція public не має execute для PUBLIC\nrevoke execute on all functions in schema public from public;\n\n-- RLS\n' ||
  (select t from rls) || E'\n\n-- політики\n' ||
  (select t from policies) || E'\n\n' ||
  (select t from triggers) || E'\n\n-- права на таблиці\n' ||
  (select t from tgrants) || E'\n\n-- права на окремі колонки\n' ||
  (select t from cgrants) || E'\n\n-- заплановані завдання (для довідки, не виконується цим файлом)\n' ||
  (select t from jobs) || E'\n'
, 'UTF8'), 'base64') as b64;
